target : hw4

hw4 : 161044067_main.cpp composedShape.cpp rectangle.cpp circle.cpp triangle.cpp polygon.cpp polyline.cpp composedShape.h rectangle.h circle.h triangle.h polygon.h polyline.cpp

	g++ 161044067_main.cpp composedShape.cpp rectangle.cpp circle.cpp triangle.cpp polygon.cpp polyline.cpp composedShape.h rectangle.h circle.h triangle.h polygon.h polyline.h -std=c++11 -o hw4

clean:
	rm hw4
