target : hw5

hw5 : 161044067_main.cpp composedShape.cpp rectangle.cpp circle.cpp triangle.cpp polygon.cpp shapes.cpp PolygonDyn.cpp PolygonVect.cpp composedShape.h rectangle.h circle.h triangle.h polygon.h shapes.h PolygonDyn.h PolygonVect.h

	g++ 161044067_main.cpp composedShape.cpp rectangle.cpp circle.cpp triangle.cpp polygon.cpp shapes.cpp PolygonDyn.cpp PolygonVect.cpp composedShape.h rectangle.h circle.h triangle.h polygon.h shapes.h PolygonDyn.h PolygonVect.h -std=c++11 -o hw5

clean:
	rm hw5
