target : hw2

hw2 : 161044067_main.cpp composedShape.cpp rectangle.cpp circle.cpp triangle.cpp composedShape.h rectangle.h circle.h triangle.h

	g++ 161044067_main.cpp composedShape.cpp rectangle.cpp circle.cpp triangle.cpp composedShape.h rectangle.h circle.h triangle.h -std=c++11 -o hw2

clean:
	rm hw2
