target : hw6

hw6 : 161044067_main.cpp GTUarray_list.cpp GTUcollection.cpp GTUhash_set.cpp GTUiterator.cpp GTUlinked_list.cpp GTUlist.cpp GTUqueue.cpp GTUset.cpp GTUset.h GTUarray_list.h GTUcollection.h GTUhash_set.h GTUiterator.h GTUlinked_list.h GTUlist.h GTUqueue.h

	g++ 161044067_main.cpp GTUarray_list.cpp GTUcollection.cpp GTUhash_set.cpp GTUiterator.cpp GTUlinked_list.cpp GTUlist.cpp GTUqueue.cpp GTUset.cpp GTUset.h GTUarray_list.h GTUcollection.h GTUhash_set.h GTUiterator.h GTUlinked_list.h GTUlist.h GTUqueue.h -std=c++11 -o hw6

clean:
	rm hw6
